# A Brief Pandas Tutorial
This notebook showcases a few useful features of the *pandas* library.
## Let's start by importing pandas:

In [23]:
import pandas as pd

## Create some data
There are a variety of ways to create a *DataFrame* object in pandas, but we will use a dictionary. Each *key* in the dictionary will become a column in the DataFrame, and each *value* contains the list of data for that column.

In [28]:
data = {
    'coffee': [20,23,19,26,30,43,40],
    'tea': [15,16,11,21,12,16,21],
    'hot chocolate': [2,5,1,0,4,4,2],
}
index = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
df = pd.DataFrame(data, index=index)
df

## Here are a couple of ways pandas allows us to examine the data:

In [29]:
df.info()

In [31]:
df.columns

In [32]:
df.describe()

## Pandas also provides some useful tools for selecting parts of the data.
### We can select a single column like this:

In [11]:
df["coffee"]

### Or a single row like this:

In [33]:
df.loc["Friday"]

### We can also select rows based on a column's value:

In [17]:
df[df["tea"] > 20]

## Pandas also integrates with Matplotlib, a comprehensive visualization library

In [34]:
import matplotlib.pyplot as plt
df.plot(kind="line", y=["coffee", "tea", "hot chocolate"])
plt.xticks(rotation = 45)
plt.show()